---
title: "class3&4"
author: "Sandrine Mfuranzima"
date: "2025-10-17"
output: html_document
---
### Regression

##### Fitting regression models with lm()
###### Simple linear regression
```{r}
data("women")
fit<-lm(weight~height, data=women)
summary(fit)
```

```{r}
women$weight
```
```{r}
fitted(fit)
```
```{r}
residuals(fit)
```
```{r}
plot(women$height,women$weight,xlab="Height (in inches)",ylab="Weight(in pounds)")
abline(fit)
```
```{r}
fit2<- lm(weight~height+I(height^2), data=women)
summary(fit2)
```
```{r}
plot(women$height,women$weight,xlab="Height (in inches)",ylab="Weight(in pounds)")
lines(women$height,fitted(fit2))
```

### Regression diagnostics
```{r}
fit<- lm(weight~height, data = women)
par(mfrow=c(2,2))
plot(fit)



```
```{r}
fit2<- lm(weight~height+I(height^2), data=women)
par(mfrow=c(2,2))
plot(fit2)
```


```{r}
newfit<-lm(weight~height+I(height^2),data=women[-c(13,15),]) 
par(mfrow=c(2,2))
plot(newfit)
```
### Exploration of mtcars data

```{r}
plot(mpg~wt,data=mtcars)
model<- lm(mpg~wt, data=mtcars)
#plot(model)
abline(model)
```

```{r}
summary(model)
```
```{r}
predict(model,newdata=data.frame(wt=6))
```
### Simulation in R

```{r}
x <- rnorm(10)
pnorm(2)
## [1] 0.9772499
x <- rnorm(10, 20, 2)
```
##### Setting the random number seed
```{r}
set.seed(1)
rnorm(5)
## [1] -0.6264538 0.1836433 -0.8356286 1.5952808 0.3295078
rnorm(5)
## [1] -0.8204684 0.4874291 0.7383247 0.5757814 -0.3053884
set.seed(1)
```
#### Simulaton a linear model
```{r}
## Always set your seed!
set.seed(20)
## Simulate predictor variable
x <- rnorm(100)
## Simulate the error term
e <- rnorm(100, 0, 2)
## Compute the outcome via the model
y <- 0.5 - 2 * x + e
plot(x, y)
```
```{r}
set.seed(1)
sample(1:10, 4)
```

```{r}
sample(1:10, 4)
## Doesn't have to be numbers
sample(letters, 5)
## Do a random permutation
sample(1:10)

sample(1:10)

## Sample w/replacement
sample(1:10, replace = TRUE)
```

### Data Visualization

##### Data source:https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita
```{r}
country<-c("Australia", "Austria", "Belgium","Canada",
"Denmark", "Finland","France","Germany",
"Greece","Ireland","Italy","Japan", "Netherland",
"New Zealand", "Norway", "Portugal", "Spain","Sweden",
"Switzerland","UK","USA")
Income.inequality<-c(7.0,4.8,4.6,5.6,4.3,3.7,5.6,5.2,6.2,6.0,6.7,3.4,5.3,6.8,3.9,8.0,5.5,4.0,5.7,7.2,8.6)
Index.HS<-c(0.07,0.01,-0.23,-0.07,-0.19,-0.43,0.05,-0.06,0.38,0.25,-0.12,-1.26,-0.51,0.29,-0.63
,1.18,-0.30,-0.83,-0.46,0.79,2.02)
GDP_WB<-c(45926,47682,43435,45066,45537,30676,39328,46401,26851,49393,35463,36319,48253,37679,65615
,28760,33629,45297,59540,40233,54630)
data.21<-data.frame(country,Income.inequality,Index.HS,GDP_WB)
plot(data.21[c("Income.inequality","Index.HS")])
```


```{r}
Index_inequality.df<-data.21[c("Income.inequality","Index.HS")]
str(Index_inequality.df)
## 'data.frame': 21 obs. of 2 variables:
## $ Income.inequality: num 7 4.8 4.6 5.6 4.3 3.7 5.6 5.2 6.2 6 ...## $ Index.HS : num 0.07 0.01 -0.23 -0.07 -0.19 -0.43 0.05-0.06 0.38 0.25 ...
(country<-data.21[,"country"])

(country.2<-data.21["country"])

str(country)

str(country.2)

plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country)
```

```{r}
plot(Index_inequality.df,pch=20) 
text(Index_inequality.df,labels=country,pos=1)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=2)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=3)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=4)
```
```{r}
plot(Index_inequality.df,pch=20)
text(Index_inequality.df,labels=country,pos=4,cex=0.8)

```

```{r}
which(country %in% c("Austria","Denmark","Germany","Netherland"))

text.left<-which(country %in% c("Austria","Denmark","Germany","Netherland"))
text.left

text.right<-setdiff(1:nrow(data.21),text.left)
text.right

pos.text<-ifelse(1:nrow(data.21)%in% text.left,2,4)
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5))
text(Index_inequality.df,labels=country,pos=pos.text,cex=0.8)
```


```{r}
which(country %in% "Germany")

text.up<-which(country %in% "Germany")
text.up

text.left<-setdiff(1:nrow(data.21),c(text.right,text.up))
text.left

pos.text<-ifelse(1:nrow(data.21) %in% text.up,3,ifelse(1:nrow(data.21)%in% text.left,2,4))
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5),ann=FALSE)
text(Index_inequality.df,labels = country,pos=pos.text,cex=0.8)
main.title<-"Income inequality vs Index of Health and Social problems"
x.lab<-"Income inequality (5th Ratio)"
y.lab<-"Index of Health and Social problems"
title(main=main.title,xlab=x.lab,ylab=y.lab)
```

```{r}
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5),ann=FALSE)
text(Index_inequality.df,labels = country,pos=pos.text,cex=0.8)
main.title<-"Income inequality vs Index of Health and Social problems"
x.lab<-"Income inequality (5th Ratio)"
y.lab<-"Index of Health and Social problems"
title(main=main.title,xlab=x.lab,ylab=y.lab)
mtext(c("Better","Worse"),side=2,at=c(-1.8,2.8),las=1)
```
```{r}
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5),ann=FALSE)
text(Index_inequality.df,labels = country,pos=pos.text,cex=0.8)
main.title<-"Income inequality vs Index of Health and Social problems"
x.lab<-"Income inequality (5th Ratio)"
y.lab<-"Index of Health and Social problems"
title(main=main.title,xlab=x.lab,ylab=y.lab)
mtext(c("Better","Worse"),side=2,at=c(-1.8,2.8),las=1)
text(x=5,y=1.5,labels=paste("r=",round(cor(Index_inequality.df[1],Index_inequality.df[2]),digits=2)))
```

```{r}
plot(Index_inequality.df,pch=20,col="red",xlim=c(3,9),ylim=c(-1.5,2.5),ann=FALSE)
text(Index_inequality.df,labels = country,pos=pos.text,cex=0.8)
main.title<-"Income inequality vs Index of Health and Social problems"
x.lab<-"Income inequality (5th Ratio)"
y.lab<-"Index of Health and Social problems"
title(main=main.title,xlab=x.lab,ylab=y.lab)
mtext(c("Better","Worse"),side=2,at=c(-1.8,2.8),las=1)
text(x=5,y=1.5,labels=paste("r=",round(cor(Index_inequality.df[1],Index_inequality.df[2]),digits=2)))
lm.ineq<-lm(Index.HS~Income.inequality,data=Index_inequality.df)
abline(lm.ineq$coef,col="blue")
```


```{r}
rm(list=ls(all=TRUE))
###set.seed(1002)
n <-30 ## number of observations
M <- 1 ## number of pathways
p<-5
z <- matrix(runif(n * p, 0, 1), nrow=n, ncol=p)
x <- 3*cos(z[, 1]) + 2*rnorm(n)
x<-as.matrix(x)
beta.true <- rep(1,ncol(x))
## pathway-response function
hfun1 <- function(zvec) (10*cos(zvec[1]) - 15*(zvec[2])^2+10*exp(-zvec[3])*zvec[4]-8*sin(zvec[5])*cos(zvec[3])+20*(zvec[1]*zvec[5]))
h1 <- apply(z, 1, hfun1) ## only depends on z1,z2,z3,z4,z5
eps <- rnorm(n)
y <-x * beta.true + h1+ eps
```








